<a href="https://colab.research.google.com/github/whiteydoublee/Colab/blob/main/Ch1.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18
이름 : 김예은
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
 - 고성능의 수치계산을 위한 파이썬 라이브러리
 - 파이썬의 기본 리스트보다 월등한 연산 성능
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [ ]:
# numpy 벡터
v1 = np.array([1, 2, 3, 4, 5])
print('v1 :', v1)

v2 = np.arange(5)
print('v2 :', v2)

v3 = np.arange(10)
print('v3 :', v3)

v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.randn(100)

# 0 ~ 9 사이의 임의의 정수
result3 = np.random.randint(10)

In [ ]:
result1, result2, result3

(array([0.03729065, 0.72635844, 0.60962435, 0.05698154, 0.03619394,
        0.06617637, 0.81734005, 0.18708402, 0.34387448, 0.32083762,
        0.7842073 , 0.97072629, 0.86778613, 0.92260383, 0.45617167,
        0.77810225, 0.43963935, 0.31247805, 0.28986967, 0.41748672,
        0.65186189, 0.78366644, 0.47071846, 0.91970072, 0.20302866,
        0.63314266, 0.1461291 , 0.42764532, 0.17297793, 0.41662753,
        0.80218333, 0.83398092, 0.45570246, 0.88561166, 0.16823258,
        0.30651746, 0.13994729, 0.08009531, 0.2940798 , 0.8951319 ,
        0.38436511, 0.42921116, 0.01170934, 0.70112738, 0.05588231,
        0.57659778, 0.33673839, 0.76965526, 0.71971275, 0.45400569,
        0.50314266, 0.05226444, 0.30660828, 0.30470974, 0.84017659,
        0.74028517, 0.76219568, 0.74876557, 0.42613106, 0.02152302,
        0.2670803 , 0.12278397, 0.44848211, 0.83978977, 0.49341147,
        0.3717033 , 0.90209284, 0.8261303 , 0.89859774, 0.22141407,
        0.23674462, 0.52994566, 0.3011104 , 0.90

In [ ]:
# numpy 행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
